# 0
# The debugging of the speed and slope pid of 
# car No.130 has completed, 300 to 450 is proved 
# to be a stable speed range for the car.
#slope_p_0: -0.4 slope_i_0: -0.5 slope_d_0: 0.3
#speed_p_0: -0.03 speed_i_0: -0.03 speed_d_0: 2

marker_0: 0
ip_0: "192.168.1.130"
port_0: 10000
slope_p_0: 0.5
slope_i_0: 0.1
slope_d_0: 0
speed_p_0: 6
speed_i_0: 0
speed_d_0: 0
target_slope_0: 220
target_speed_0: 1
target_point_x_0: 0
target_point_y_0: 0


#IP:192.168.114  slope(p:-0.4;i:-0.7;d:1)   speed(p:-0.04;i:-0.05;d:2)


#IP:192.168.8.131 slope(p:-0.4;i:-0.2;d:1) speed(p:-0.02;i:-0.02;d:2)
# 1
# The debugging of the speed and slope pid of 
# car No.131 has completed,300 to 450 is proved to be a stable speed range for the car.
marker_1: 1
ip_1: "192.168.1.131"
port_1: 10000
slope_p_1: 0.5
slope_i_1: 0.1
slope_d_1: 0
speed_p_1: 6
speed_i_1: 0
speed_d_1: 0
target_slope_1: 220
target_speed_1: 1
target_point_x_1: 0
target_point_y_1: 0
#IP:192.168.8.131 slope_p:-0.4 slope_i:-1.0 slope_d:0.5
#marker_1: 1
#ip_1: "192.168.8.114" port_p:0.5;port_i:0.8;port_d:0.2;
#speed_p:-0.03;speed_i:-0.03;speed_i:

# 2
marker_2: 2
ip_2: "192.168.1.132"
port_2: 10000
slope_p_2: 0.5
slope_i_2: 0.1
slope_d_2: 0
speed_p_2: 6
speed_i_2: 0
speed_d_2: 0
target_slope_2: 235
target_speed_2: 0
target_point_x_2: 0
target_point_y_2: 0
#speed_p_2: -0.06
#speed_i_2: -0.06
#speed_d_2: 0.02

# 3
#marker_1: 1
#ip_3: "192.168.8.132"
#slope_p_3: -0.5  slope_i_3: -0.8slope_d_3: 0.2
#speed_p_3: -0.05 speed_i_3: -0.04 speed_d_3: 2
marker_3: 3
ip_3: "192.168.1.133"
port_3: 10000
slope_p_3: 0.2
slope_i_3: 0
slope_d_3: 0
speed_p_3: 0
speed_i_3: 0
speed_d_3: 0
target_slope_3: 0
target_speed_3: 0
target_point_x_3: 0
target_point_y_3: 0

#4
marker_4: 4
ip_4: "192.168.1.134"
port_4: 10000
slope_p_4: 0.2
slope_i_4: 0.
slope_d_4: 0
speed_p_4: -5
speed_i_4: -1.5
speed_d_4: 0
target_slope_4: 180
target_speed_4: 0
target_point_x_4: 0
target_point_y_4: 0
#ip:192.168.8.113 slope(p:0.6,i:0.8,d:0.5) speed(p:-0.03,i:-0.03,d:2)

# # 4
#  marker_4: 4
#  ip_4: "192.168.8.119"
#  port_4: 10000
#  slope_p_4: 0.5
#  slope_i_4: 0.7
#  slope_d_4: 0.2
#  speed_p_4: -0.01
#  speed_i_4: -0.015
#  speed_d_4: 2
#  target_slope_4: 90
#  target_speed_4: 40

# 5
#the debugging of slope pid of 
# this car has completed , but there is someting wrong with the speed pid. slope p -0.5 i -0.7 d 0.05
# speed p -0.01 i -0.01 d 0.03
#we guess 
marker_5: 5
ip_5: "192.168.1.135"
port_5: 10000
slope_p_5: 0.2
slope_i_5: 0
slope_d_5: 0
speed_p_5: 5
speed_i_5: 0
speed_d_5: 0
target_slope_5: 180
target_speed_5: 0
target_point_x_5: 0
target_point_y_5: 0
# 6
marker_6: 6
ip_6: "192.168.1.136"
port_6: 10000
slope_p_6: 0.2
slope_i_6: 0
slope_d_6: 0
speed_p_6: 0.1
speed_i_6: 0.2
speed_d_6: 0
target_slope_6: 180
target_speed_6: 0
target_point_x_6: 0
target_point_y_6: 0


#IP:192.168.8.137   slope(p:-0.5;i:-0.8;d:0.2)  speed(p:-0.03;i:-0.03;d:2)

# # 7
# marker_7: 7
# ip_7: "192.168.8.116"
# port_7: 10000
# slope_p_7: -0.64
# slope_i_7: 0.97
# slope_d_7: 0.03
# speed_p_7: -0.06
# speed_i_7: -0.06
# speed_d_7: 0.02
# target_slope_7: 270
# target_speed_7: 0
# target_point_x_7: 100.85
# target_point_y_7: 200.32

# 7
marker_7: 7
ip_7: "192.168.1.137"
port_7: 10000
slope_p_7: 0.2
slope_i_7: 0
slope_d_7: 0
speed_p_7: 0.1
speed_i_7: 0.3
speed_d_7: 0
target_slope_7: 180
target_speed_7: 0
target_point_x_7: 0
target_point_y_7: 0

# 8
marker_8: 8
ip_8: "192.168.1.138"
port_8: 10000
slope_p_8: 0.2
slope_i_8: 0.1
slope_d_8: 0.2
speed_p_8: 0.1
speed_i_8: 0.3
speed_d_8: 0
target_slope_8: 180
target_speed_8: 0
target_point_x_8: 0
target_point_y_8: 0
# 9
marker_9: 9
ip_9: "192.168.1.139"
port_9: 10000
slope_p_9: -0.2
slope_i_9: -0.3
slope_d_9: 0
speed_p_9: -0.13
speed_i_9: -0.13
speed_d_9: 0
target_slope_9: 180
target_speed_9: 0
target_point_x_9: 0
target_point_y_9: 0